apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:k8nishant/argocd-poc.git
    targetRevision: main
    path: hello-app

  destination:
    server: https://kubernetes.default.svc
    namespace: poc-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true