apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:k8nishant/argocd-poc.git
      revision: main
      directories:
      - path: apps/*

  template:
    metadata:
      name: '{{path.basename}}-root'
    spec:
      project: default
      source:
        repoURL: git@github.com:k8nishant/argocd-poc.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true