apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-registry
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:k8nishant/argocd-poc.git
    targetRevision: main
    path: apps/local-registry-app

  destination:
    server: https://kubernetes.default.svc
    namespace: registry

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true