apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinybert-mlops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:k8nishant/argocd-poc.git
    targetRevision: main
    path: apps/mlops-app/template

  destination:
    server: https://kubernetes.default.svc
    namespace: ml-inference

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true