apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tinybert
  namespace: ml-inference
spec:
  selector:
    matchLabels:
      app: tinybert
  endpoints:
  - port: http
    path: /metrics
    interval: 15s