apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.17.0   # use latest chart version
      helm:
        releaseName: airflow
        timeout: 15m
        valueFiles:
          - $values/apps/airflow-app/values.yaml
          
    - repoURL: git@github.com:k8nishant/argocd-poc.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
